CUDA_VISIBLE_DEVICES=0 python generate_poison.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0015.cfg &&
CUDA_VISIBLE_DEVICES=0 python finetune_and_test.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0015.cfg &&

CUDA_VISIBLE_DEVICES=0 python generate_poison.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0016.cfg &&
CUDA_VISIBLE_DEVICES=0 python finetune_and_test.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0016.cfg &&

CUDA_VISIBLE_DEVICES=0 python generate_poison.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0017.cfg &&
CUDA_VISIBLE_DEVICES=0 python finetune_and_test.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0017.cfg &&

CUDA_VISIBLE_DEVICES=0 python generate_poison.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0018.cfg &&
CUDA_VISIBLE_DEVICES=0 python finetune_and_test.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0018.cfg &&

CUDA_VISIBLE_DEVICES=0 python generate_poison.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0019.cfg &&
CUDA_VISIBLE_DEVICES=0 python finetune_and_test.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0019.cfg &&

CUDA_VISIBLE_DEVICES=0 python generate_poison.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0020.cfg &&
CUDA_VISIBLE_DEVICES=0 python finetune_and_test.py cfg_CIFAR/singlesource_singletarget_binary_finetune/experiment_0020.cfg
